### ISSUE TITLE
Bower manage support ?

### ISSUE THREAD

**Issue by thejourneyoflife** [gvas/knockout-jqueryui#44]
Please add bower support ,Thanks

**Comment by gvas** [comment]
I have added support for bower, but it turned out that @jrcamp already registered the knockout-jqueryui bower package. I've tried to contact him (jrcamp/knockout-jqueryui-bower#1), I hope he will respond in a couple of days. If not, then I will try to convince the bower folks to transfer the ownership of the package to me.

**Comment by jrcamp** [comment]
Sorry, I didn't get the e-mail (or missed it) for the issue created in my repo but saw this one. I'll take care of it now.

**Comment by gvas** [comment]
@jrcamp: Thank you for your cooperation.

**Comment by thejourneyoflife** [comment]
@gvas Thanks.
